# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/Paddle.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/Ball.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/clockDivider.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/ClockDivider5000.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/VGAController.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/SevSeg_4digit.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/videoGen.sv
  D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/sources_1/new/pongGame.sv
}
read_xdc D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.001/Desktop/project_2/project_2.srcs/constrs_1/new/const.xdc]

synth_design -top pongGame -part xc7a35tcpg236-1
write_checkpoint -noxdef pongGame.dcp
catch { report_utilization -file pongGame_utilization_synth.rpt -pb pongGame_utilization_synth.pb }
